"""Artifact-level gates shared by visual-generator and presentation stages."""

from __future__ import annotations

import json
import re
from pathlib import Path
from typing import Any


CANDIDATES = ("candidate-a", "candidate-b", "candidate-c")
CANDIDATE_IMAGES = ("cover.png", "section.png", "content.png", "result.png")
SLIDE_SPEC_FIELDS = (
    "slide_number",
    "page_type",
    "title",
    "key_message",
    "layout",
    "visual_style",
    "template_application_mode",
    "image_prompt",
    "style_reference_prompt",
    "reference_images",
    "dominant_visual",
    "deterministic_text_overlay",
    "deterministic_chart_overlay",
    "layout_flexibility",
    "visual_inheritance",
    "prohibited_inheritance",
    "referenced_metrics",
    "speaker_notes_path",
    "qa_checklist",
)


class BuildBlocked(RuntimeError):
    pass


def expected_visual_tool(output_dir: Path) -> str:
    """Read the declared visual generator; keep image2 as the legacy compatibility default."""
    for filename in ("deck-config.confirmed.yaml", "deck-config.yaml"):
        path = Path(output_dir) / filename
        if not path.is_file():
            continue
        for line in path.read_text(encoding="utf-8").splitlines():
            if line.strip().startswith("visual_generator:"):
                value = line.split(":", 1)[1].strip().strip("\"'")
                if value:
                    return value
    return "image2"


def read_mapping(path: Path) -> dict[str, Any]:
    if not path.is_file():
        return {}
    text = path.read_text(encoding="utf-8")
    try:
        value = json.loads(text)
        return dict(value) if isinstance(value, dict) else {}
    except json.JSONDecodeError:
        result: dict[str, Any] = {}
        lines = text.splitlines()
        for index, raw in enumerate(lines):
            line = raw.strip()
            if not line or line.startswith("#") or ":" not in line:
                continue
            key, value = line.split(":", 1)
            value = value.strip().strip("\"'")
            if not value:
                base_indent = len(raw) - len(raw.lstrip())
                items = []
                for following in lines[index + 1:]:
                    if not following.strip():
                        continue
                    indent = len(following) - len(following.lstrip())
                    if indent <= base_indent:
                        break
                    stripped = following.strip()
                    if stripped.startswith("-"):
                        items.append(stripped[1:].strip().strip("\"'"))
                result[key.strip()] = items if items else ""
            else:
                result[key.strip()] = value
        return result


def validate_style_candidates(output_dir: Path) -> list[str]:
    output_dir = Path(output_dir)
    errors: list[str] = []
    root = output_dir / "style-candidates"
    actual = sorted(path.name for path in root.glob("candidate-*") if path.is_dir()) if root.is_dir() else []
    if actual != list(CANDIDATES):
        errors.append(f"manual mode requires exactly {list(CANDIDATES)}; found {actual}")
    expected_outputs: set[str] = set()
    for candidate in CANDIDATES:
        candidate_dir = root / candidate
        for name in (*CANDIDATE_IMAGES, "style-profile.yaml"):
            if not (candidate_dir / name).is_file():
                errors.append(f"{candidate} is missing {name}")
        for name in CANDIDATE_IMAGES:
            expected_outputs.add((candidate_dir / name).relative_to(output_dir).as_posix())

    manifest_path = output_dir / "image-generation-manifest.json"
    if not manifest_path.is_file():
        errors.append("missing image-generation-manifest.json")
        return errors
    try:
        manifest = json.loads(manifest_path.read_text(encoding="utf-8"))
    except (OSError, UnicodeError, json.JSONDecodeError) as exc:
        errors.append(f"invalid image-generation-manifest.json: {exc}")
        return errors
    calls = manifest.get("calls", []) if isinstance(manifest, dict) else []
    successful_outputs: set[str] = set()
    required_tool = expected_visual_tool(output_dir)
    for index, call in enumerate(calls, start=1):
        if not isinstance(call, dict):
            errors.append(f"manifest call {index} is not an object")
            continue
        for field in ("tool_name", "model_or_tool_version", "prompt_path", "reference_images", "output_path", "timestamp", "success", "error"):
            if field not in call:
                errors.append(f"manifest call {index} is missing {field}")
        if call.get("tool_name") != required_tool:
            errors.append(f"manifest call {index} was not generated by {required_tool}")
        if call.get("model_or_tool_version") in (None, "", "unknown"):
            errors.append(f"manifest call {index} has no auditable model_or_tool_version")
        if call.get("success") is not True:
            errors.append(f"manifest call {index} did not succeed")
        if not call.get("reference_images"):
            errors.append(f"manifest call {index} has no reference_images")
        if call.get("tool_name") == required_tool and call.get("success") is True:
            successful_outputs.add(str(call.get("output_path", "")))
    missing_manifest_outputs = sorted(expected_outputs - successful_outputs)
    if missing_manifest_outputs:
        errors.append(f"candidate images lack successful {required_tool} records: " + ", ".join(missing_manifest_outputs))
    return errors


def assert_preview_generation_allowed(output_dir: Path) -> None:
    output_dir = Path(output_dir)
    config = read_mapping(output_dir / "deck-config.confirmed.yaml") or read_mapping(output_dir / "deck-config.yaml")
    if config.get("workflow_mode") == "auto" and config.get("selection_mode") == "direct":
        if not (output_dir / "deck-config.confirmed.yaml").is_file():
            raise BuildBlocked("auto/direct preview generation requires deck-config.confirmed.yaml")
        return
    selected_path = output_dir / "selected-style.yaml"
    if not selected_path.is_file():
        raise BuildBlocked("preview generation requires a user-selected candidate")
    selected = read_mapping(selected_path)
    if selected.get("selected_by") != "user":
        raise BuildBlocked("selected-style.yaml selected_by must be user")
    if not selected.get("template_profile"):
        raise BuildBlocked("selected-style.yaml requires template_profile")
    candidate = selected.get("selected_candidate")
    if candidate not in CANDIDATES:
        raise BuildBlocked("selected candidate is not one of candidate-a, candidate-b, candidate-c")
    errors = validate_style_candidates(output_dir)
    if errors:
        raise BuildBlocked("; ".join(errors))


def validate_slide_specs(output_dir: Path) -> tuple[list[Path], list[str]]:
    specs_dir = Path(output_dir) / "slide-specs"
    specs = sorted(specs_dir.glob("slide-*.yaml")) if specs_dir.is_dir() else []
    errors: list[str] = []
    if not specs:
        errors.append("slide-specs/slide-XX.yaml files are required")
        return specs, errors
    expected_names = [f"slide-{index:02d}.yaml" for index in range(1, len(specs) + 1)]
    actual_names = [path.name for path in specs]
    if actual_names != expected_names:
        errors.append(f"slide-specs filenames must be contiguous; found {actual_names}")
    for spec in specs:
        payload = read_mapping(spec)
        filename_match = re.fullmatch(r"slide-(\d+)", spec.stem)
        if filename_match and payload.get("slide_number") not in (None, ""):
            expected_number = str(int(filename_match.group(1)))
            if str(payload.get("slide_number")).strip() != expected_number:
                errors.append(f"{spec.name} slide_number must match its filename ({expected_number})")
        for field in SLIDE_SPEC_FIELDS:
            if field not in payload:
                errors.append(f"{spec.name} is missing {field}")
        for field in (
            "page_type", "title", "key_message", "layout", "visual_style", "template_application_mode",
            "image_prompt", "style_reference_prompt",
            "dominant_visual", "deterministic_text_overlay", "deterministic_chart_overlay",
            "layout_flexibility", "visual_inheritance", "prohibited_inheritance", "speaker_notes_path",
        ):
            if payload.get(field) in (None, "", "[]"):
                errors.append(f"{spec.name} requires non-empty {field}")
        if payload.get("reference_images") in (None, "", "[]", []):
            errors.append(f"{spec.name} requires non-empty reference_images")
        if payload.get("qa_checklist") in (None, "", "[]", []):
            errors.append(f"{spec.name} requires non-empty qa_checklist")
        if not payload.get("image_prompt"):
            errors.append(f"{spec.name} cannot generate preview without image_prompt")
    return specs, errors
